### ISSUE TITLE
[Inquiry] Keyboard detection

### ISSUE THREAD

**Issue by sam20e** [denilsonsa/crx-reload-tab#15] opened 2023-10-31 03:40 UTC
Hello,

Could you please confirm whether this script includes keyboard detection? To clarify, if I'm reloading a tab (for example, domain.com), and I navigate to that tab and begin typing, will the extension continue to reload the tab or will it cease reloading due to keyboard activity?

Thank you.

**Comment by denilsonsa** [comment] 2023-10-31 07:28
No, it currently doesn't support that  feature. So, yes, it will reload regardless of the page interaction.

I'm closing this as a duplicate of #8.

**Closed as completed by denilsonsa** 2023-10-31 07:28 UTC
