### ISSUE TITLE
Timer stops if you close the browser tab and reopen it again unlike other timer apps

### ISSUE THREAD

**Issue by mathkkad** [denilsonsa/crx-reload-tab#13] opened 2023-08-25 13:02 UTC
Hi!

I really enjoy this timer app. Unfortunately if you close the browser page where the timer is active and reopen it again, the timer is not running anymore, unlike other timer apps that I tested that keep running on that page if i reopen that page again. This is especially useful if I need to see other pages and come back or if the browser crashes and I have to reload everything again / power outage and browsers closes

Maybe you can add this functionality so it can keep the timer running on the page even if you close the tab and reopen it again.

Thank you!

**Comment by denilsonsa** [comment] 2023-08-25 14:05
Closing this as duplicate of #2

**Closed as completed by denilsonsa** 2023-08-25 14:05 UTC
